site_name: Bashing Logs

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

docs_dir: docs
